### ISSUE TITLE
events added by addEventListener for "gattserverdisconnected" does not fire

### ISSUE THREAD

**Issue by boogerlad** [urish/web-bluetooth-polyfill#26]
I have not tested with other events, but maybe all events are broken as well. On a linux machine: https://googlechrome.github.io/samples/web-bluetooth/device-disconnect-async-await.html

clicking disconnect will result in
```
Requesting Bluetooth Device...
Connecting to Bluetooth Device...
> Bluetooth Device connected
Disconnecting from Bluetooth Device...
> Bluetooth Device disconnected
```

but doing the same thing on windows will result in 
```
Requesting Bluetooth Device...
Connecting to Bluetooth Device...
> Bluetooth Device connected
Disconnecting from Bluetooth Device...
```

**Comment by urish** [comment]
Thanks for reporting! Can you please check if the fix in master works for you?

**Comment by boogerlad** [comment]
yup :)

**Comment by urish** [comment]
Great! About shutting down the device - it worked for me at some point in the past, I'll try to see if I can reproduce
