### ISSUE TITLE
compilation error: vs 2017

### ISSUE THREAD

**Issue by dmazzella** [urish/web-bluetooth-polyfill#29]
Hi, i have tried to build bleserver with vs 2017 but i have this error:

1>c:\users\damiano\desktop\web-bluetooth-polyfill\bleserver\bleserver\stdafx.cpp : fatal error C1107: impossibile trovare l'assembly 'platform.winmd': specificare il percorso di ricerca dell'assembly utilizzando /AI o impostando la variabile d'ambiente LIBPATH

any hint?

**Comment by urish** [comment]
Check out the [AdditionalUsingDirectories](https://github.com/urish/web-bluetooth-polyfill/blob/6e159ccd082174af5fe8fd13c165f9720cdcf72e/BLEServer/BLEServer/BLEServer.vcxproj#L93), do they exist on your system? 


I have the `platform.winmd` file in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\vcpackages. You may need to adjust the path per your system
