### ISSUE TITLE
readValue does not fire a `characteristicvaluechanged` event

### ISSUE THREAD

**Issue by bluetooth-mdw** [urish/web-bluetooth-polyfill#33]
Hi, I'm trying to use this polyfill for the first time. Nice work btw!

writeValue is working fine but readValue is not. I have a protocol analyzer and can see that the expected attribute protocol messages are exchanged with my peripheral and the expected characteristic value is being returned. But I don't get a callback to the registered function.

The same web page works fine from Chrome on Android and on Mac OS.

During service discovery I do this:

```
if (characteristic.uuid == MODEL_NUMBER_STRING) {
	model_number_string = characteristic;
	has_model_name_string = true;
	model_number_string.addEventListener('characteristicvaluechanged',
		onModelNumberStringChanged);
}
```

The callback function looks like this:

```
function onModelNumberStringChanged(event) {
	console.log("onModelNumberStringChanged");
	var value = event.target.value;
	var data = new Uint8Array(value.buffer);
	model_number_string = new TextDecoder("utf-8").decode(data);
	console.log(model_number_string);
	document.getElementById("model_number").innerHTML = model_number_string;
}
```

And I request the read of the characteristic with:

```
model_number_string.readValue();
```
Any ideas?

**Comment by urish** [comment]
Hi,

Thank you!

For the notifications, did you remember to call the `startNotifications()` method?

Then, for reading, can you please [debug the background page of the extension](https://github.com/urish/web-bluetooth-polyfill/issues/21#issuecomment-308990559) and show the logs that you get there? Also, check if you get any output on the devtools console of your web page.

**Comment by bluetooth-mdw** [comment]
Hi Urish, I'm not trying to use notifications. I'm just reading a characteristic value. 

The debug logs show that the read result is being received. I'm just not getting a callback to the handler function onModelNumberStringChanged.

```
Sent native message: {device: "BluetoothLE#BluetoothLE7c:7a:91:db:f3:43-b8:27:eb:c5:e9:31", service: "{0000180a-0000-1000-8000-00805f9b34fb}", characteristic: "{00002a24-0000-1000-8000-00805f9b34fb}", cmd: "read", _id: 130}
background.js:24 Received native message: 
```

By the way, I'm using notifications with a different characteristic and that is working fine. It's just the use of characteristic.readValue which is not working.

**Comment by urish** [comment]
I see, currently the event listener is only invoked if you use notifications. I will check what the spec says about this - currently, the way it works with reading would be to wait for the promise to resolve:

    model_number_string.readValue().then(value => {
        // do something with value
    });

**Comment by urish** [comment]
I see that [according to the spec](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattcharacteristic-readvalue), `readValue()` should indeed fire a `characteristicvaluechanged` event. I will add it

**Comment by bluetooth-mdw** [comment]
Great, thank you. I'm preparing a series of tutorials for bluetooth.com. I'll mention your polyfill :-)

**Comment by urish** [comment]
Nice, and nice to meet you by the way! Are you also on Twitter?

**Comment by bluetooth-mdw** [comment]
Likewise :-)

@bluetooth_mdw

Very interested in seeing Web Bluetooth adopted across all the browsers!

**Comment by urish** [comment]
awesome! 

Then perhaps you can chime in this discussion: https://twitter.com/Espruino/status/923555356835504128

**Comment by urish** [comment]
Can you check if the fix does the trick for you?

**Comment by bluetooth-mdw** [comment]
a) Works a treat - thanks for the rapid service!

b) I changed to the resolved promise pattern anyway since this is clearly more in keeping with the normal use of the API.

Marvellous!

**Comment by urish** [comment]
You are welcome :)

**Comment by urish** [comment]
not related - do you know if there is some ongoing process for a standard UART BLE service?

**Comment by bluetooth-mdw** [comment]
I don't think there is. It's a common request though.

**Comment by urish** [comment]
Okay, thanks!
