### ISSUE TITLE
Another "Error: Attempting to use a disconnected port object"

### ISSUE THREAD

**Issue by ChewieWookie** [urish/web-bluetooth-polyfill#36]
Hello,

I read and tried all issues here that are connected to this error. Unfortunately none solution worked for me. 

1. I have 1703 Windows 10
2. I have Visual C++ installed ( newer than in instruction, comes from VS 2017 )
3. I followed instruction with BLEServer 0.3.6 ( proper folder Web Bluetooth Polyfill, copied the Id into manifest, executed register )
4. BLEServer runs correctly manually
![image](https://user-images.githubusercontent.com/10144360/32069082-6d42eaa2-ba88-11e7-8ba2-c73d1bcda805.png)

Still I got this error and I am totally confused. 
StackTrace: 
![image](https://user-images.githubusercontent.com/10144360/32069131-8ce85d24-ba88-11e7-9048-c09ee4a2b03d.png)

Still trying to figure this one out but maybe you have some more insight.

Regards

**Comment by urish** [comment]
Can you [please enable debug logging](https://github.com/urish/web-bluetooth-polyfill/issues/21#issuecomment-308990559) and post the full log?

**Comment by ChewieWookie** [comment]
Yeah I forgot. Sorry

`Sent native message: {cmd: "scan", _id: 1}
extensions::messaging:102 Uncaught (in promise) Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:102:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:138:26)
    at Promise (chrome-extension://joeddpfhohdknijmlmomdhealbjfbgem/background.js:16:20)
    at new Promise (<anonymous>)
    at nativeRequest (chrome-extension://joeddpfhohdknijmlmomdhealbjfbgem/background.js:7:12)
    at startScanning (chrome-extension://joeddpfhohdknijmlmomdhealbjfbgem/background.js:106:9)
    at requestDevice (chrome-extension://joeddpfhohdknijmlmomdhealbjfbgem/background.js:161:5)
    at port.onMessage.addListener (chrome-extension://joeddpfhohdknijmlmomdhealbjfbgem/background.js:333:13)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)`

That's all I get from debug logs. 

`[BLE::Info] Requesting devices with options 
Object
acceptAllDevices:true
filters:[]
optionalServices:["generic_access"]
__proto__:Object`

Here is log from app console.

Hope it helps.

**Comment by ChewieWookie** [comment]
Little update. 

I managed to connect with BLEServer. In my case I needed to give permissions for those files for every user in windows ( they unpacked the way that I always needed admin rights to run or modify them ). So now chrome can start it after several tries of reloading the extension. 

However now I have other problem.

```
Uncaught TypeError: Cannot read property 'impl' of undefined
    at getPrivateImpl (extensions::utils:119:30)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:137:20)
    at window.addEventListener.event (chrome-extension://joeddpfhohdknijmlmomdhealbjfbgem/content.js:31:14)
```

Debug logs shows nothing for that.

**Comment by urish** [comment]
Thanks for the update!

Can you please send a pull request for the [troubleshooting section](https://github.com/urish/web-bluetooth-polyfill#troubleshooting) in favor of future users who may encounter this issue?

regarding the other problem - seems like the `port` object of chrome (the one we use for communicating between the content script and the background page of the extension) is misbehaving. Can you try to `console.log(port, event);` just before the `postMessage` in content.js line 31?

**Comment by ChewieWookie** [comment]
Sure.

I have already figured out second problem. It was my really stupid mistake so don't bother ;)

**Comment by urish** [comment]
Awesome! So is it working for you now?

**Comment by ChewieWookie** [comment]
Yep!

**Comment by abd0o0o** [comment]
@ChewieWookie , 
Please, how did you solve your problem of the disconnected port object?

**Comment by ChewieWookie** [comment]
> @ChewieWookie ,
> Please, how did you solve your problem of the disconnected port object?

In my case it was a matter of BLE server not running because Windows prevented Chrome from starting it. 

I guess the best way for you to continue is to setup in windows all possible rights for BLE server files and disable Smart Screen on windows. Maybe it is possible to disable it for one application, I don't remember now if that is a possibility. BLE Server is a program not signed by Microsoft so SmartScreen will block it's every execution, unless disabled.
