### ISSUE TITLE
BLEServer 0.4.0 - StreamValues not working after reconnection 

### ISSUE THREAD

**Issue by ChewieWookie** [urish/web-bluetooth-polyfill#41]
Hi,

I have a problem with BLEServer 0.4.0.

When I get a disconnect event, I reconnects with device but after that I don't get any values updates from characteristic.

I am attaching two log files that maybe will clarify something.

[1513120274081-0.3.6.log](https://github.com/urish/web-bluetooth-polyfill/files/1553680/1513120274081-0.3.6.log)
[1513120532893-0.4.0.log](https://github.com/urish/web-bluetooth-polyfill/files/1553682/1513120532893-0.4.0.log)

There is one error in logs from 0.4.0 but it is connected to Uncought (in Promise). It comes from types/web-bluetooth writeValue method. Attaching logs for that too. (Stacktrace strarts from message Writing to characteristic failed because: undefined. Tried to catch it just for being sure)

[localhost-1513121263253-chromeLogs-0.3.6.log](https://github.com/urish/web-bluetooth-polyfill/files/1553668/localhost-1513121263253-chromeLogs-0.3.6.log)
[localhost-1513121460043-chromeLogs-0.4.0.log](https://github.com/urish/web-bluetooth-polyfill/files/1553669/localhost-1513121460043-chromeLogs-0.4.0.log)

From those logs I cannot figure out what's wrong unfortunately :/ Maybe you will make something out of them. 

I don't rule out that it is my mistake. I upgraded by myself angular-web-bluetooth module because I got tired of waiting for that to happen, so maybe I made a mistake somwhere there. And there still may be bug in my code ( however the same code works fine on BLEServer 0.3.6 and not 0.4.0)

Hope you can help me :)

**Comment by urish** [comment]
Hi, from the 0.4.0 log it seems like you are trying to write to a read-only characteristic, which explains why you get the error:

`background.js:16 Sent native message: {device: "BluetoothLE#BluetoothLE00:1a:7d:da:71:11-4a:f9:e2:64:80:b5", service: "{0000180f-0000-1000-8000-00805f9b34fb}", characteristic: "{00002a19-0000-1000-8000-00805f9b34fb}", value: Array(1), cmd: "write", …}`

the 0.3.6 log does not have this write. Can you set a breakpoint on [writeValue](https://github.com/urish/web-bluetooth-polyfill/blob/4abd1af7ec090a4cc8009c14f6cb278934bcc3ed/extension/polyfill.js#L138) and see who is trying to do this write?

**Comment by ChewieWookie** [comment]
Yeah I could but that is actually irrelevant to this problem. Yes this error happens because I am trying to write to characteristic battery_level. I used one method that does that and I was unaware of that. Localhost log from version 0.3.6 does not have this write as I corrected the code.

However, what is important part here is that on 0.3.6 you can see that after successful reconnection I am reciving values again, while on 0.4.0 I do not ( and I am notifying them for sure ).

**Comment by urish** [comment]
Can you please check if the following version fixes the issue for you?

https://github.com/urish/web-bluetooth-polyfill/releases/download/0.4.1-beta/BLEServer-0.4.0.1-b867fe1.zip

**Comment by ChewieWookie** [comment]
Unfortunately yes, it's still happening :( 

I have in logs `[BLE::Info] Starting notifications of "battery_level"` which shows after requesting streamValue, but no new value comes. 

In BLEServer logs it looks like that: 

```
Received native message: {_type: "disconnectEvent", device: "BluetoothLE#BluetoothLE00:1a:7d:da:71:11-63:52:2c:09:0c:3e"}

Sent native message: {address: "63522c090c3e", cmd: "connect", _id: 110}

Received native message: {_type: "response", _id: 110, result: "BluetoothLE#BluetoothLE00:1a:7d:da:71:11-63:52:2c:09:0c:3e"}

Sent native message: {device: "BluetoothLE#BluetoothLE00:1a:7d:da:71:11-63:52:2c:09:0c:3e", service: "{0000180f-0000-1000-8000-00805f9b34fb}", cmd: "services", _id: 111}

Received native message: {_type: "response", _id: 111, result: Array(1)}

Sent native message: {device: "BluetoothLE#BluetoothLE00:1a:7d:da:71:11-63:52:2c:09:0c:3e", service: "{0000180f-0000-1000-8000-00805f9b34fb}", cmd: "characteristics", _id: 112}

Received native message: {_type: "response", _id: 112, result: Array(1)}

Sent native message: {device: "BluetoothLE#BluetoothLE00:1a:7d:da:71:11-63:52:2c:09:0c:3e", service: "{0000180f-0000-1000-8000-00805f9b34fb}", characteristic: "{00002a19-0000-1000-8000-00805f9b34fb}", cmd: "subscribe", _id: 113}

Received native message: {_type: "response", _id: 113, result: 2}result: 2_id: 113_type: "response"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()

Received native message: {_type: "disconnectEvent", device: "BluetoothLE#BluetoothLE00:1a:7d:da:71:11-63:52:2c:09:0c:3e"}

```
As you can see I request service and characteristic after disconnection and then there is subscribe command to characteristic but no new value came. Only next disconnection event

**Comment by urish** [comment]
I see... It does not reproduce for me after the fix (before the fix I did have some problem with reconnecting).

Do you want me to send you instructions how to further debug BLEServer? It involves installing Visual Studio 2017 (the free edition), but other than that it's pretty straight forward and will give us more understanding into what goes wrong....

**Comment by ChewieWookie** [comment]
I've got Visual Studio, however I will need decompiler I guess. 

Do you have any suggestions?

**Comment by urish** [comment]
No need for decompiler - just compile BLEServer yourself (sources are [here](https://github.com/urish/web-bluetooth-polyfill/tree/master/BLEServer)), and then point the extension to use the EXE file that you compiled. Make sure you compile in *Debug* mode.

Finally, with the extension running, you can Attach to it from VS 2017:
![image](https://user-images.githubusercontent.com/892318/34228252-ca701828-e5d8-11e7-81c1-4a72f1b21bfa.png)

then choose BLEServer.exe from the list, and you should be able to set breakpoint, watches, etc.
![image](https://user-images.githubusercontent.com/892318/34228340-ff68aed2-e5d8-11e7-95cc-8edcb3a70842.png)

Two points of interest are:

[Writing to the descriptor to enable notifications](https://github.com/urish/web-bluetooth-polyfill/blob/b867fe18392266632657d010893addd1289ffc41/BLEServer/BLEServer/BLEServer.cpp#L281) and the [event listener for value changed](https://github.com/urish/web-bluetooth-polyfill/blob/b867fe18392266632657d010893addd1289ffc41/BLEServer/BLEServer/BLEServer.cpp#L297)

I'd love to learn about your findings!

**Comment by ChewieWookie** [comment]
Sorry for late answer.

So far I was unlucky with finding anything. 

I was just able to debug your code and I can describe what's happening.

After first connection everything works fine. I have a success from WriteClientCharacteristicConfigurationDescriptorAsync and then everything gets setup ( Creation of subscriptionId and then setting ValueChanged handler ). After that I get notifications and everything works fine. 

After reconnection this the key for this subscription is in a map ( characteristicsSubscriptionMap ) so I get value returned from this map. After that I never once hit the breakpoint inside ValueChanged handler. 

I cannot say much more. Debbuger does not show me characteristic object. It's full of pointers to god know where. I just get there a memory address: 0x00000254ebdfc360 and information <No type information available in symbol file for Windows.Devices.Bluetooth.dll>. I guess debugger cannot load some dll's or debug symbols for dll's and it just shows pointer value and not the object it points to :( 

So I have no way of finding out if this event handler is still in it's place or if this subscriptionId changes or is invalid. 

I can see that after that you return in a response the returned subscriptionId. I assume that this event handler needs to be setup once and it is there ( that is usually what happen in .Net ) But maybe it is rewritten in some way. Or maybe it gets unsubscribed ( I saw that in unsubscribeRequest there is part of the code that does that ).

It also looks that in disconnectRequest you clear the characteristic maps ( characteristicsListenerMap and characteristicsSubscriptionMap ). But after disconnection and my reconnection attempt this if:

`if (characteristicsSubscriptionMap->HasKey(key))` 

passes with true ( in subscribeRequest method )

I hope that will help at least a little.

**Comment by urish** [comment]
Thanks for sharing you findings! To be honest, I am probably not going to keep working on this polyfill for long, as it seems like the Chromium guys have started working on the actual implementation in Chrome:

https://chromium.googlesource.com/chromium/src/+log/master/device/bluetooth

One workaround that may be good for your needs would be to kill and re-connect to BLEServer.exe whenever you disconnect from a device, or to have one BLEServer.exe instance per device. I'm not sure how much work this would require, but a good place to start is the `background.js` script.

Cheers, and Happy New Year :-)

**Comment by urish** [comment]
This polyfill is now deprecated - please use Chrome Canary with native Web Bluetooth instead.
