### ISSUE TITLE
Problem with pairing ..

### ISSUE THREAD

**Issue by Diam0ndR** [urish/web-bluetooth-polyfill#42]
Hello there,
I recently bought a Puck device but I can't use the web Bluetooth poly-fill. I followed all the steps and everything seems to work correctly.. Although my Puck shows while searching and when it shows i press pair button this is what i get as result..
![untitled](https://user-images.githubusercontent.com/34928196/35174959-1d3e8b08-fd7a-11e7-8bdd-c10a3e6809e0.png)

**Comment by urish** [comment]
This polyfill is now deprecated - please use Chrome Canary with native Web Bluetooth instead.
