### ISSUE TITLE
Puck.js

### ISSUE THREAD

**Issue by baudenfj** [urish/web-bluetooth-polyfill#43]
I am having trouble connecting my puck.js to the website! I followed every step and believe to have installed web-bluetooth-polyfill correctly. When I go to the console in the Webapp I can see the following message 
<BLE> ERROR: NotFoundError: Bluetooth adapter not available.
The regular IDE work great on windows for the puck! I can pair everytime! 
I can not reconstruct but I was able to see the puck in the we pairing window but we I started to pair the console gave me the error that the device was not supported!

Very frustrating... trying a MAC next!

**Comment by urish** [comment]
This polyfill is now deprecated - please use Chrome Canary with native Web Bluetooth instead.
