### ISSUE TITLE
attribute requires authentication - should trigger pairing

### ISSUE THREAD

**Issue by smartyw** [urish/web-bluetooth-polyfill#44]
Hi

when I access an attribute which requires authentication, without having paired the device, I expect this to trigger the pairing procedure. This is what happens when I test on Chrome OS and I believe is what the Bluetooth spec says. But when I do this on Windows 10 with this polyfill I get a dialogue which says that "The attribute requires authentication before it can be read or written".

![image](https://user-images.githubusercontent.com/1387793/41334584-133f775e-6ede-11e8-8b68-5e4062cd62a7.png)

**Comment by urish** [comment]
This polyfill is now deprecated - please use Chrome Canary with native Web Bluetooth instead.
