### ISSUE TITLE
send 0x0101 to record access control point  characteristic "Impossible to write this attribute" 

### ISSUE THREAD

**Issue by merylb** [urish/web-bluetooth-polyfill#49]
hello,
i try to send 0x0101 to record access control point  characteristic but I get this error "Impossible to write this attribute" I need to know  is that's an error in the the value 0x0101 or somthing else.

**Comment by urish** [comment]
Sounds like the characteristic is read-only? Can you try to write this value from the nRF Connect app (to the same characteristic) and see what you get?

**Comment by merylb** [comment]
I'm sûre that my characteristic is writable here is a screenshot of its details is one of pulse oximetry service characteristics.
![recordaccess](https://user-images.githubusercontent.com/33625598/43715064-15964e2e-9977-11e8-8069-6ed820275692.png)

**Comment by merylb** [comment]
please any help i'am blocked in this stage

**Comment by urish** [comment]
1. Can you test the same Web Bluetooth code on an Android device or Mac computer to compare?
2. What is the value of `bool writeWithoutResponse` in BLEServer?

**Comment by urish** [comment]
The polyfill is now deprecated - please use Chrome Canary with native Web Bluetooth instead.
