### ISSUE TITLE
Error: Catastrophic failure  Catastrophic failure

### ISSUE THREAD

**Issue by thangta** [urish/web-bluetooth-polyfill#51]
Hi, I get an error in Chrome Canary in Window10. He is the screen short and debug log

[pdfhjjeijpigdmfdchmkjllglhmppnkl-1534837281579. log](https://github.com/urish/web-bluetooth-polyfill/files/2305626/pdfhjjeijpigdmfdchmkjllglhmppnkl-1534837281579.log)
![image](https://user-images.githubusercontent.com/13417944/44392975-abf06480-a55d-11e8-8b37-4e2a521ca5a7.png)

**Comment by urish** [comment]
Please report this issue in Chrome's bug tracker: http://crbug.com/new 

Thank you!
