### ISSUE TITLE
why the bleserver is running and found nothing

### ISSUE THREAD

**Issue by ShiverZm** [urish/web-bluetooth-polyfill#65]
as i know ,the server  means publish a service ,and other center can found it?but my other device found none.

**Comment by ShiverZm** [comment]
in a addtion.i use web-bluetooth-polyfill ,the light blue also cannot not find the service

**Comment by urish** [comment]
Hi, this project is deprecated and is no longer being updated. As the notice in the README says, Chrome now supports Web Bluetooth natively.

The BLEServer does not publish a Bluetooth service, it's just a program that lets the polyfill interact with the Native Bluetooth API on Windows 10. The name may be a bit confusing, sorry about that.
